import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NavbarMobile } from "@/components/ui/NavbarMobile";
import { Navbar } from "@/components/ui/Navbar";
import { Footer } from "@/components/ui/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Cavalsync, le réseau du lien entre cavaliers et centres équestres",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="myTheme">
      <body className={inter.className}>
        <header className="hidden md:block">
          <Navbar />
        </header>
        {children}
        <Footer />
        <div className="block md:hidden">
          <NavbarMobile />
        </div>
      </body>
    </html>
  );
}
